<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TractorRental.Locacao.Domain\TractorRental.Locacao.Domain.csproj" />
    <ProjectReference Include="..\TractorRental.SharedKernel\TractorRental.SharedKernel.csproj" />
  </ItemGroup>
</Project>
